# Generated by Django 4.2.2 on 2023-07-03 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_scoresbycategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.category'),
        ),
    ]
